<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AERai.Seller.Domain\AERai.Seller.Domain.csproj" />
    <ProjectReference Include="..\AERai.Seller.SpApiClient\AERai.Seller.SpApiClient.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
