// <auto-generated />
using System;
using AERai.Seller.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AERai.Seller.Infrastructure.Migrations
{
    [DbContext(typeof(SellerDbContext))]
    [Migration("20260802193541_AddCatalog")]
    partial class AddCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AERai.Seller.Domain.CatalogItem", b =>
                {
                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentAsin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Asin");

                    b.HasIndex("ParentAsin");

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("AERai.Seller.Domain.CatalogParent", b =>
                {
                    b.Property<string>("ParentAsin")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ParentAsin");

                    b.ToTable("CatalogParents");
                });

            modelBuilder.Entity("AERai.Seller.Domain.FinancialEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmazonOrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventSubType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmazonOrderId", "EventSubType", "PostedDate");

                    b.ToTable("FinancialEvents");
                });

            modelBuilder.Entity("AERai.Seller.Domain.InventorySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sku", "State", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("InventorySnapshots");
                });

            modelBuilder.Entity("AERai.Seller.Domain.Order", b =>
                {
                    b.Property<string>("AmazonOrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OrderTotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTotalCurrency")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AmazonOrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AERai.Seller.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmazonOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ItemPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemPriceCurrency")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmazonOrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AERai.Seller.Domain.Product", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CostOfGoods")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Sku");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AERai.Seller.Domain.SettlementReport", b =>
                {
                    b.Property<string>("SettlementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DepositDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FinancialEventGroupEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FinancialEventGroupStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("SettlementId");

                    b.ToTable("SettlementReports");
                });

            modelBuilder.Entity("AERai.Seller.Domain.SyncMetadata", b =>
                {
                    b.Property<string>("SyncJobName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSuccessfulSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LastSyncSucceeded")
                        .HasColumnType("INTEGER");

                    b.HasKey("SyncJobName");

                    b.ToTable("SyncMetadata");
                });

            modelBuilder.Entity("AERai.Seller.Domain.CatalogItem", b =>
                {
                    b.HasOne("AERai.Seller.Domain.CatalogParent", null)
                        .WithMany("Items")
                        .HasForeignKey("ParentAsin")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AERai.Seller.Domain.OrderItem", b =>
                {
                    b.HasOne("AERai.Seller.Domain.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("AmazonOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AERai.Seller.Domain.CatalogParent", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AERai.Seller.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
