namespace AERai.Web.Domain.Ingestion;

/// <summary>
/// The SP-API reports the app ingests automatically, and how each is obtained.
/// </summary>
public enum AmazonReportType
{
    /// <summary>
    /// <c>GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL</c>: requested on demand for a time window
    /// (orders created or updated since the last successful run).
    /// </summary>
    Orders = 1,

    /// <summary><c>GET_FBA_MYI_ALL_INVENTORY_DATA</c>: requested on demand; a point-in-time snapshot.</summary>
    FbaInventory = 2,

    /// <summary>
    /// <c>GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2</c> (one row per amount): generated by Amazon on its own schedule (it cannot
    /// be requested), so runs list newly available reports and ingest any not seen before.
    /// </summary>
    Settlements = 3,

    /// <summary>
    /// <c>GET_RESERVED_INVENTORY_DATA</c>: requested on demand; a point-in-time snapshot of why stock
    /// is reserved (customer orders, FC transfers, FC processing).
    /// </summary>
    FbaReservedInventory = 4,
}
