using AERai.Seller.Application.Abstractions;
using AERai.Seller.Application.Reports;
using AERai.Seller.SpApiClient.Reports;
using Microsoft.Extensions.Logging;

namespace AERai.Seller.Application.Sync;

public interface ISettlementSyncService
{
    Task SyncAsync(IProgress<string>? progress = null, CancellationToken cancellationToken = default);
}

/// <summary>
/// Pulls Amazon settlement/payout reports via the Reports API and upserts them locally. Follows the
/// request -> poll -> download -> parse -> idempotent-upsert pattern documented in the
/// add-report-sync-job skill, mirroring InventorySyncService.
///
/// Requests GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 (the "long" layout: one amount-type /
/// amount-description / amount triple per row), NOT GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE — a live
/// SP-API pull on 2026-10-05 confirmed the latter is the "wide" layout (shipment-fee-type,
/// price-amount, item-related-fee-amount, ... columns) that SettlementReportParser can't read. Amazon
/// generates both for every settlement, so requesting _V2 loses no data.
///
/// Unlike GET_FBA_INVENTORY_PLANNING_DATA, settlement reports are
/// auto-generated by Amazon on each ~14-day settlement period rather than computed fresh on request.
/// This service requests one via CreateReportAsync with a lookback date range (wide enough to always
/// cover at least the most recent settlement period), matching this app's existing sync pattern for
/// consistency — verify against a real sync run that createReport actually returns the intended
/// settlement's data for this report type; if Amazon's behavior differs (e.g. only already-generated
/// reports can be listed, not freshly requested), this will need to switch to a report-listing call
/// instead once that's added to ReportsApiClient.
/// </summary>
public sealed class SettlementSyncService(
    ReportsApiClient reportsApiClient,
    ISettlementRepository settlementRepository,
    ISyncMetadataRepository syncMetadataRepository,
    TimeProvider timeProvider,
    ILogger<SettlementSyncService> logger) : ISettlementSyncService
{
    public const string SyncJobName = "Settlements";
    private const string ReportType = "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2";

    // Wide enough to reliably span at least one full ~14-day settlement period even if a sync is
    // run somewhat late.
    private static readonly TimeSpan LookbackWindow = TimeSpan.FromDays(30);

    private static readonly TimeSpan PollInterval = TimeSpan.FromSeconds(10);
    private static readonly TimeSpan PollTimeout = TimeSpan.FromMinutes(10);

    public async Task SyncAsync(IProgress<string>? progress = null, CancellationToken cancellationToken = default)
    {
        try
        {
            progress?.Report("Settlements: requesting report...");
            var now = timeProvider.GetUtcNow();
            var reportId = await reportsApiClient.CreateReportAsync(
                ReportType, dataStartTime: now - LookbackWindow, dataEndTime: now, cancellationToken);

            var status = await PollUntilDoneAsync(reportId, progress, cancellationToken);
            if (status.ReportDocumentId is null)
            {
                throw new InvalidOperationException($"Report {reportId} finished as {status.ProcessingStatus} with no document.");
            }

            progress?.Report("Settlements: downloading report...");
            var document = await reportsApiClient.GetReportDocumentAsync(status.ReportDocumentId, cancellationToken);
            var content = await reportsApiClient.DownloadReportDocumentAsync(document, cancellationToken);

            progress?.Report("Settlements: parsing and saving...");
            var rows = TsvReportParser.Parse(content);
            var (settlements, lineItems) = SettlementReportParser.Parse(rows, now);
            if (settlements.Count > 0 && lineItems.Count == 0)
            {
                logger.LogWarning(
                    "Settlement report {ReportId} contained {SettlementCount} settlement(s) but no detail line items",
                    reportId, settlements.Count);
            }

            await settlementRepository.UpsertAsync(settlements, lineItems, cancellationToken);
            await syncMetadataRepository.RecordResultAsync(SyncJobName, succeeded: true, errorMessage: null, cancellationToken);

            progress?.Report($"Settlements: done, {settlements.Count} settlement(s) / {lineItems.Count} line item(s) synced.");
            logger.LogInformation(
                "Settlement sync completed: {SettlementCount} settlement(s) / {LineItemCount} line item(s) upserted",
                settlements.Count, lineItems.Count);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Settlement sync failed");
            await syncMetadataRepository.RecordResultAsync(SyncJobName, succeeded: false, ex.Message, cancellationToken);
            throw;
        }
    }

    private async Task<ReportsApiClient.ReportStatus> PollUntilDoneAsync(
        string reportId, IProgress<string>? progress, CancellationToken cancellationToken)
    {
        var deadline = timeProvider.GetUtcNow() + PollTimeout;
        var pollCount = 0;

        while (true)
        {
            pollCount++;
            progress?.Report($"Settlements: waiting for report to process (check {pollCount})...");
            var status = await reportsApiClient.GetReportAsync(reportId, cancellationToken);

            switch (status.ProcessingStatus)
            {
                case "DONE":
                    return status;
                case "CANCELLED":
                case "FATAL":
                    throw new InvalidOperationException($"Report {reportId} ended with status {status.ProcessingStatus}.");
            }

            if (timeProvider.GetUtcNow() > deadline)
            {
                throw new TimeoutException($"Report {reportId} did not finish within {PollTimeout}.");
            }

            await Task.Delay(PollInterval, timeProvider, cancellationToken);
        }
    }
}
